# Generated by Django 2.2.5 on 2019-09-30 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20190930_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
